version: 0.2

env:
  shell: bash
phases:
  pre_build:
    commands:
      - |
        aws ecr wait image-scan-complete --repository-name $ECR_REPO --image-id imageTag=$IMAGE_TAG
        aws ecr describe-image-scan-findings --repository-name $ECR_REPO --image-id imageTag=$IMAGE_TAG | jq '.imageScanFindings.findings[]'
        if [ $(echo $?) -eq 0 ]; then
          SCAN_FINDINGS=$(aws ecr describe-image-scan-findings --repository-name $ECR_REPO --image-id imageTag=$IMAGE_TAG | jq '.imageScanFindings.findingSeverityCounts')
          CRITICAL=$(echo $SCAN_FINDINGS | jq '.CRITICAL')
          HIGH=$(echo $SCAN_FINDINGS | jq '.HIGH')
          MEDIUM=$(echo $SCAN_FINDINGS | jq '.MEDIUM')
          LOW=$(echo $SCAN_FINDINGS | jq '.LOW')
          INFORMATIONAL=$(echo $SCAN_FINDINGS | jq '.INFORMATIONAL')
          UNDEFINED=$(echo $SCAN_FINDINGS | jq '.UNDEFINED')
          if [ $CRITICAL != null ] || [ $HIGH != null ]; then
            echo Docker image contains vulnerabilities at CRITICAL or HIGH level
            exit 1
          fi
        fi
